import React, { useEffect, useState } from "react";
import { format } from "date-fns";
import {
    CaretSortIcon,
    ChevronDownIcon,
    ChevronRightIcon,
    DotsHorizontalIcon,
} from "@radix-ui/react-icons";
import {
    flexRender,
    getCoreRowModel,
    getFilteredRowModel,
    getPaginationRowModel,
    getSortedRowModel,
    useReactTable,
} from "@tanstack/react-table";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
    DropdownMenu,
    DropdownMenuCheckboxItem,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table";
import { DatePicker } from "@/components/ui/date-picker";
import { MeditationObjectPopover } from "./MeditationObjectPopover";
import { useDispatch } from "react-redux";
import { createGoal, updateGoal, deleteGoal } from "../../slices/GoalsSlice";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select";
import { v4 as uuidv4 } from 'uuid';
import { statusOptions } from "../../constants/constants";

export function GoalsTable({ goals = [], isSubGoals = false, parentGoalId = null, onSelectedGoals = null }) {
    const dispatch = useDispatch();

    const initialGoalState = {
        id: '', // This will be generated by the backend
        status: 'NotStarted',
        activity: {
            title: ''
        },
        meditationObject: {
            title: '',
            description: '',
            subType: '',
        },
        dueDate: '', // Ensure this is in the correct date format
        completedDate: null,
        parentGoalId: parentGoalId,
        childGoals: [],
    };

    const [data, setData] = useState(goals);
    const [sorting, setSorting] = useState([]);
    const [columnFilters, setColumnFilters] = useState([]);
    const [columnVisibility, setColumnVisibility] = useState({});
    const [rowSelection, setRowSelection] = useState({});
    const [isEditing, setIsEditing] = useState(null);
    const [isCreating, setIsCreating] = useState(false);
    const [expandedRows, setExpandedRows] = useState({});
    const [localData, setLocalData] = useState({});

    useEffect(() => {
        if (!isSubGoals) {
            const organizedData = organizeGoals(goals);
            setData(organizedData);
        }
    }, [goals]);

    useEffect(() => {
        const selectedGoals = table.getSelectedRowModel().rows.map(row => row.original);
        onSelectedGoals ? onSelectedGoals(selectedGoals) : '';
    }, [rowSelection]);

    const handleDeleteGoal = (id) => {
        // setData(data.filter((goal) => goal.id !== id));
        dispatch(deleteGoal(id));
    };

    const organizeGoals = (goals) => {
        return goals.filter(goal => goal.parentGoalId == null);
    };
    const prepareGoalForCreation = (g) => {

        var preparedGoal = {
            status: g.status,
            activity: {
                title: g.activity.title
            },
            meditationObject: {
                title: g.meditationObject.title,
                description: g.meditationObject.description,
                subType: g.meditationObject.subType,
            },
            dueDate: g.dueDate,
            completedDate: g.completedDate,
            parentGoalId: g.parentGoalId,
            childGoals: g.childGoals.map(child => prepareGoalForCreation(child))
        };

        return preparedGoal;
    };

    const prepareGoalForUpdating = (g) => {

        var preparedGoal = {
            id: g.id,
            status: g.status,
            activity: {
                title: g.activity.title
            },
            meditationObject: {
                title: g.meditationObject.title,
                description: g.meditationObject.description,
                subType: g.meditationObject.subType,
            },
            dueDate: g.dueDate,
            completedDate: g.completedDate,
            parentGoalId: g.parentGoalId,
            childGoals: g.childGoals.map(child => prepareGoalForCreation(child))
        };

        return preparedGoal;
    };

    const handleCreateGoal = () => {
        const newId = `[new]-${uuidv4()}`;
        const newGoalData = { ...initialGoalState, id: newId }; // Ensure activity has title
        setLocalData((prevData) => ({
            ...prevData,
            [newId]: newGoalData,
        }));
        setData([...data, newGoalData]);
        // * Testing
        // console.log(localData);
        setIsEditing(newId);
        setIsCreating(true);
    };

    const handleEditGoal = (id) => {
        setIsEditing(id);
        const goalToEdit = data.find(goal => goal.id === id);
        if (goalToEdit) {
            setLocalData((prevData) => ({
                ...prevData,
                [id]: goalToEdit,
            }));
        }
    };

    const handleSaveGoal = () => {

        var goalToSave = localData[isEditing];

        if (goalToSave) {
            if (isCreating) {
                const preparedGoal = prepareGoalForCreation(goalToSave);
                dispatch(createGoal(preparedGoal));
            } else {
                const preparedGoal = prepareGoalForUpdating(goalToSave);
                console.log("Goal to save before passing to updateGoal():");
                console.log(preparedGoal);
                dispatch(updateGoal(preparedGoal));
            }
        }

        setData((prevData) =>
            prevData.map((goal) => (goal.id === isEditing ? goalToSave : goal))
        );

        setLocalData((prevData) => {
            const { [isEditing]: removed, ...rest } = prevData;
            return rest;
        });
        setIsEditing(null);
        setIsCreating(false);
    };

    const handleInputChange = (e, id) => {
        const { name, value } = e.target;
        setLocalData((prevData) => ({
            ...prevData,
            [id]: {
                ...prevData[id],
                [name]: value,
            },
        }));
    };

    const handleActivityChange = (e, id) => {
        const { value } = e.target;
        setLocalData((prevData) => ({
            ...prevData,
            [id]: {
                ...prevData[id],
                activity: {
                    // ...prevData[id]?.activity,
                    title: value,
                },
            },
        }));
    };

    const handleMeditationObjectChange = (value, id) => {
        setLocalData((prevData) => ({
            ...prevData,
            [id]: {
                ...prevData[id],
                meditationObject: value,
            },
        }));
    };

    const handleDateChange = (date, id) => {
        const formattedDate = date.toISOString().split('T')[0];
        setLocalData((prevData) => ({
            ...prevData,
            [id]: {
                ...prevData[id],
                dueDate: formattedDate,
            },
        }));
    };

    const handleToggleExpand = (id) => {
        setExpandedRows((prev) => ({
            ...prev,
            [id]: !prev[id],
        }));
    };

    const columns = React.useMemo(() => [
        {
            id: 'select',
            header: ({ table }) => (
                <Checkbox
                    checked={table.getIsAllPageRowsSelected() || (table.getIsSomePageRowsSelected() && 'indeterminate')}
                    onCheckedChange={(value) => table.toggleAllPageRowsSelected(!!value)}
                    aria-label="Select all"
                />
            ),
            cell: ({ row }) => (
                <Checkbox
                    checked={row.getIsSelected()}
                    onCheckedChange={(value) => row.toggleSelected(!!value)}
                    aria-label="Select row"
                />
            ),
            enableSorting: false,
            enableHiding: false,
        },
        {
            id: 'toggle',
            cell: ({ row }) => (
                <Button variant="ghost" onClick={() => handleToggleExpand(row.original.id)} className="p-0">
                    {expandedRows[row.original.id] ? (
                        <ChevronDownIcon className="h-4 w-4" />
                    ) : (
                        <ChevronRightIcon className="h-4 w-4" />
                    )}
                </Button>
            ),
        },
        {
            accessorKey: 'status',
            header: ({ column }) => (
                <Button variant="ghost" onClick={() => column.toggleSorting(column.getIsSorted() === 'asc')}>
                    Status
                    <CaretSortIcon className="ml-2 h-4 w-4" />
                </Button>
            ),
            cell: ({ row }) => {
                const isEditingRow = isEditing === row.original.id;

                const statusValue = localData[row.original.id]?.status || row.getValue('status');
                return isEditingRow ? (
                    <Select onValueChange={(value) => handleInputChange({ target: { name: 'status', value } }, row.original.id)}>
                        <SelectTrigger className="w-full">
                            <SelectValue placeholder={statusValue} />
                        </SelectTrigger>
                        <SelectContent>
                            {statusOptions.map(option => (
                                <SelectItem key={option} value={option}>
                                    {option}
                                </SelectItem>
                            ))}
                        </SelectContent>
                    </Select>
                ) : (
                    <div className="capitalize">{statusValue}</div>
                );
            },
        },
        {
            accessorKey: 'activity',
            header: ({ column }) => (
                <Button variant="ghost" onClick={() => column.toggleSorting(column.getIsSorted() === 'asc')}>
                    Activity
                    <CaretSortIcon className="ml-2 h-4 w-4" />
                </Button>
            ),
            cell: ({ row }) => {
                const isEditingRow = isEditing === row.original.id;
                const activityTitle = localData[row.original.id]?.activity?.title || row.getValue('activity').title;

                return isEditingRow ? (
                    <Input
                        name="activity"
                        value={activityTitle}
                        onChange={(e) => handleActivityChange(e, row.original.id)}
                        className="w-full"
                    />
                ) : (
                    <div>{activityTitle}</div>
                );
            },
        },
        {
            accessorKey: 'meditationObject',
            header: ({ column }) => (
                <Button variant="ghost" onClick={() => column.toggleSorting(column.getIsSorted() === 'asc')}>
                    Meditation Object
                    <CaretSortIcon className="ml-2 h-4 w-4" />
                </Button>
            ),
            cell: ({ row }) => {
                const isEditingRow = isEditing === row.original.id;
                const meditationObject = localData[row.original.id]?.meditationObject || row.getValue('meditationObject');
                return isEditingRow ? (
                    <MeditationObjectPopover className="w-full"
                        observableObject={meditationObject}
                        onSave={(updatedObject) => handleMeditationObjectChange(updatedObject, row.original.id)}
                        buttonClass="w-full"
                    />
                ) : (
                    <div>{meditationObject?.title}</div>
                );
            },
        },
        {
            accessorKey: 'dueDate',
            header: ({ column }) => (
                <Button variant="ghost" onClick={() => column.toggleSorting(column.getIsSorted() === 'asc')}>
                    Due Date
                    <CaretSortIcon className="ml-2 h-4 w-4" />
                </Button>
            ),
            cell: ({ row }) => {
                const isEditingRow = isEditing === row.original.id;
                const dueDateValue = localData[row.original.id]?.dueDate || row.getValue('dueDate');
                const dueDate = dueDateValue ? new Date(dueDateValue) : null;

                return isEditingRow ? (
                    <DatePicker
                        initialDate={dueDate}
                        onDateChange={(date) => handleDateChange(date, row.original.id)}
                    />
                ) : (
                    <div>{dueDate ? format(dueDate, 'yyyy-MM-dd') : ''}</div>
                );
            },
        },
        {
            id: 'actions',
            enableHiding: false,
            cell: ({ row }) => {
                const isEditingRow = isEditing === row.original.id;
                return isEditingRow ? (
                    <Button variant="ghost" className="h-8 w-8 p-0" onClick={handleSaveGoal}>
                        Save
                    </Button>
                ) : (
                    <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                            <Button variant="ghost" className="h-8 w-8 p-0">
                                <span className="sr-only">Open menu</span>
                                <DotsHorizontalIcon className="h-4 w-4" />
                            </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                            <DropdownMenuItem onClick={() => handleEditGoal(row.original.id)}>Edit</DropdownMenuItem>
                            <DropdownMenuItem onClick={() => handleDeleteGoal(row.original.id)}>Delete</DropdownMenuItem>
                        </DropdownMenuContent>
                    </DropdownMenu>
                );
            },
        },
    ], [isEditing, expandedRows, localData]);

    const table = useReactTable({
        data: data,
        columns,
        onSortingChange: setSorting,
        onColumnFiltersChange: setColumnFilters,
        getCoreRowModel: getCoreRowModel(),
        getPaginationRowModel: getPaginationRowModel(),
        getSortedRowModel: getSortedRowModel(),
        getFilteredRowModel: getFilteredRowModel(),
        onColumnVisibilityChange: setColumnVisibility,
        onRowSelectionChange: setRowSelection,
        state: {
            sorting,
            columnFilters,
            columnVisibility,
            rowSelection,
            editGoalId: isEditing,
        }
    });

    return (
        <div className="w-full">
            <div className="flex items-center py-4">
                <Input
                    placeholder="Filter activities..."
                    value={(table.getColumn("activity")?.getFilterValue() ?? "")}
                    onChange={(event) =>
                        table.getColumn("activity")?.setFilterValue(event.target.value)
                    }
                    className="max-w-sm"
                />
                <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                        <Button variant="outline" className="ml-auto">
                            Columns <ChevronDownIcon className="ml-2 h-4 w-4" />
                        </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                        {table
                            .getAllColumns()
                            .filter((column) => column.getCanHide())
                            .map((column) => {
                                return (
                                    <DropdownMenuCheckboxItem
                                        key={column.id}
                                        className="capitalize"
                                        checked={column.getIsVisible()}
                                        onCheckedChange={(value) =>
                                            column.toggleVisibility(!!value)
                                        }
                                    >
                                        {column.id}
                                    </DropdownMenuCheckboxItem>
                                );
                            })}
                    </DropdownMenuContent>
                </DropdownMenu>
            </div>

            <div className="rounded-md border">
                <Table>
                    <TableHeader>
                        {table.getHeaderGroups().map((headerGroup) => (
                            <TableRow key={headerGroup.id}>
                                {headerGroup.headers.map((header) => {
                                    return (
                                        <TableHead key={header.id} className="text-center">
                                            {header.isPlaceholder
                                                ? null
                                                : flexRender(
                                                    header.column.columnDef.header,
                                                    header.getContext()
                                                )}
                                        </TableHead>
                                    );
                                })}
                            </TableRow>
                        ))}
                    </TableHeader>

                    <TableBody>
                        {table.getRowModel().rows?.length ? (
                            <>
                                {table.getRowModel().rows.map((row) => (
                                    <React.Fragment key={row.id}>
                                        <TableRow key={`row-${row.id}`} data-state={row.getIsSelected() && "selected"}>
                                            {row.getVisibleCells().map((cell) => (
                                                <TableCell key={cell.id} className="text-center">
                                                    {flexRender(
                                                        cell.column.columnDef.cell,
                                                        cell.getContext()
                                                    )}
                                                </TableCell>
                                            ))}
                                        </TableRow>
                                        {expandedRows[row.original.id] && (
                                            <TableRow key={`child-${row.original.id}`}>
                                                <TableCell colSpan={columns.length}>
                                                    <div className="ml-8 mr-8">
                                                        <GoalsTable goals={row.original.childGoals} isSubGoals={true} parentGoalId={row.original.id} />
                                                    </div>
                                                </TableCell>
                                            </TableRow>
                                        )}
                                    </React.Fragment>
                                ))}
                            </>
                        ) : (
                            <TableRow key="no-results">
                                <TableCell colSpan={columns.length} className="h-24 text-center">
                                    No results.
                                </TableCell>
                            </TableRow>
                        )}

                        {/* Add Button */}
                        <TableRow key="add-button">
                            <TableCell colSpan={columns.length} className="text-left">
                                <Button variant="outline" className="w-full" onClick={handleCreateGoal}>
                                    Add Goal
                                </Button>
                            </TableCell>
                        </TableRow>
                    </TableBody>
                </Table>
            </div>

            <div className="flex items-center justify-end space-x-2 py-4">
                <div className="flex-1 text-sm text-muted-foreground">
                    {table.getFilteredSelectedRowModel().rows.length} of{" "}
                    {table.getFilteredRowModel().rows.length} row(s) selected.
                </div>
                <div className="space-x-2">
                    <Button
                        variant="outline"
                        size="sm"
                        onClick={() => table.previousPage()}
                        disabled={!table.getCanPreviousPage()}
                    >
                        Previous
                    </Button>
                    <Button
                        variant="outline"
                        size="sm"
                        onClick={() => table.nextPage()}
                        disabled={!table.getCanNextPage()}
                    >
                        Next
                    </Button>
                </div>
            </div>
        </div>
    );
}
